use Bdjuridico 

CREATE TABLE TipoPessoa (
TIPID INT IDENTITY (1,1) primary key, 
TIPDescrição Varchar(100) NOT NULL, 
)

CREATE TABLE  Processo (
PROID INT IDENTITY (1,1) primary key, 
PRORELATO Varchar(1000) NOT NULL, 
PRODATA DATETIME 
)


CREATE TABLE Pessoa ( 
PESID INT IDENTITY (1,1)primary key, 
PESNOME Varchar (100) NOT NULL, 
PESCPF Varchar (20) NOT NULL, 
PESCNPJ Varchar (20), 
PESSEXO Varchar  (100) NOT NULL,  
) 

ALTER TABLE PESSOA 
ADD PESTELEFONE VARCHAR(30); 


CREATE TABLE PESSOAPROCESSO(
PESID INT NOT NULL, 
PROID INT NOT NULL,
TIPID INT NOT NULL, 
DATAVINCULO DATETIME
CONSTRAINT PK_PESSOAPROCESSO PRIMARY KEY (PESID, PROID) , 

CONSTRAINT FK_PESSOAPROCESSO_PESSOA FOREIGN KEY(PESID)
     REFERENCES PESSOA(PESID), 

 CONSTRAINT FK_PESSOAPROCESSO_PROID FOREIGN KEY(PROID)
     REFERENCES PROCESSO(PROID),

  CONSTRAINT FK_PESSOAPROCESSO_TIPO FOREIGN KEY(TIPID) 
      REFERENCES TIPOPESSOA(TIPID), 

  ) 

  ALTER TABLE PESSOA 
ADD PESTELEFONE VARCHAR(30);

INSERT PESSOA (PESNOME, PESCPF, PESCNPJ, PESSEXO)
VALUES ('REGI', '04265' , NULL, 'INDECISO')

GO
INSERT TIPOPESSOA VALUES ('REU') 
GO 
INSERT PROCESSO VALUES ('PORCARIA', getDATE()) 
select * from pessoa  
select * from processo 
select * from TIPOPESSOA 
insert PESSOAPROCESSO VALUES (1,1,1,getDATE()) 
insert PESSOAPROCESSO VALUES (1,2,1,getDATE()) 